version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/ROOT-2.1.0.RELEASE.war ROOT.war
artifacts:
  files:
    - ROOT.war
    - .ebextensions/**/*
