version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/ROOT-0.0.1-SNAPSHOT.war ROOT-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - ROOT-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*
